# Generated by Django 5.0.6 on 2026-07-03 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FosterVolunteer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('species_preferences', models.JSONField(blank=True, default=list)),
                ('can_handle_medical_needs', models.BooleanField(default=False)),
                ('can_handle_behavioral_needs', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foster_volunteers', to='shelters.shelter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foster_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'shelter')},
            },
        ),
        migrations.CreateModel(
            name='FosterAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('agreement_document', models.FileField(blank=True, null=True, upload_to='foster_agreements/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foster_assignments', to='animals.animal')),
                ('foster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fosters.fostervolunteer')),
            ],
        ),
    ]
