# Generated by Django 6.0.6 on 2026-07-15 17:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='pets/photos/')),
                ('care_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('dosage', models.CharField(blank=True, max_length=80)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='pet_profiles.pet')),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_conditions', models.TextField(blank=True)),
                ('emergency_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_summary', to='pet_profiles.pet')),
            ],
            options={
                'verbose_name_plural': 'Medical summaries',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(default=django.utils.timezone.localdate)),
                ('record_type', models.CharField(choices=[('checkup', 'Checkup'), ('treatment', 'Treatment'), ('lab', 'Lab result'), ('surgery', 'Surgery'), ('prescription', 'Prescription'), ('other', 'Other')], default='checkup', max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('veterinarian', models.CharField(blank=True, max_length=120)),
                ('attachment', models.FileField(blank=True, upload_to='pets/medical_records/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pet_profiles.pet')),
            ],
            options={
                'ordering': ['-record_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=120)),
                ('administered_on', models.DateField(blank=True, null=True)),
                ('next_due_on', models.DateField(blank=True, null=True)),
                ('veterinarian', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pet_profiles.pet')),
            ],
            options={
                'ordering': ['next_due_on', '-administered_on', 'vaccine_name'],
            },
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner', 'name'], name='pet_profile_owner_i_da57dc_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['pet', 'record_date'], name='pet_profile_pet_id_b5983b_idx'),
        ),
    ]
