# Generated by Django 6.0.6 on 2026-07-11 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('dosage_info', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medicines/')),
                ('pharmacy_name', models.CharField(blank=True, default='Main Clinic Pharmacy', max_length=150)),
                ('pharmacy_contact', models.CharField(blank=True, max_length=50)),
                ('pharmacy_hours', models.CharField(blank=True, default='Mon-Fri: 8am - 6pm', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('appointment', 'Appointment'), ('vaccination', 'Vaccination'), ('message', 'Message'), ('community', 'Community Alert'), ('prescription', 'Prescription'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
