# Generated by Django 6.0.6 on 2026-07-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_accessory_signupotp_vetprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetprofile',
            name='specialization',
            field=models.CharField(blank=True, default='General Practice', max_length=150),
        ),
    ]
