# Generated by Django 6.0.6 on 2026-07-15 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_vetprofile_specialization'),
        ('pet_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pet_profiles.pet'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pet_profiles.pet'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
