# Generated by Django 6.0.6 on 2026-07-15 19:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_appointment_pet_alter_prescription_pet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
