# Generated by Django 6.0.6 on 2026-07-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_pharmacyprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
