# Generated by Django 6.0.6 on 2026-07-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='pharmacy',
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='pharma_partner_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('vet', 'Veterinarian')], default='user', help_text='Determines which profile (UserProfile / VetProfile) this account owns.', max_length=10),
        ),
        migrations.DeleteModel(
            name='PharmacyProfile',
        ),
    ]
