# Generated by Django 6.0.6 on 2026-07-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_pharmacy_add_vet_pharma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessory',
        ),
    ]
