# Generated by Django 6.0.6 on 2026-08-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetprofile',
            name='clinic_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
