# Generated by Django 6.0.6 on 2026-08-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_vetprofile_clinic_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('khalti', 'Khalti'), ('manual', 'Manual')], default='khalti', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pidx',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
