# Generated by Django 6.0.6 on 2026-08-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_payment_method_alter_payment_pidx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
