# Generated by Django 5.0.6 on 2026-07-03 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('bird', 'Bird'), ('small_animal', 'Small Animal'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=150)),
                ('secondary_breed', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('approximate_age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('personality_traits', models.JSONField(blank=True, default=list)),
                ('energy_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('good_with_dogs', models.BooleanField(blank=True, null=True)),
                ('good_with_cats', models.BooleanField(blank=True, null=True)),
                ('good_with_children', models.BooleanField(blank=True, null=True)),
                ('is_house_trained', models.BooleanField(blank=True, null=True)),
                ('is_spayed_or_neutered', models.BooleanField(default=False)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('is_microchipped', models.BooleanField(default=False)),
                ('special_needs', models.TextField(blank=True)),
                ('caretaker_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('on_hold', 'On Hold'), ('fostered', 'In Foster Care'), ('adopted', 'Adopted'), ('not_available', 'Not Available')], default='available', max_length=15)),
                ('intake_date', models.DateField(auto_now_add=True)),
                ('intake_type', models.CharField(blank=True, choices=[('stray', 'Stray'), ('surrender', 'Owner Surrender'), ('transfer', 'Transfer'), ('born_in_care', 'Born in Care')], max_length=20)),
                ('adoption_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals_created', to=settings.AUTH_USER_MODEL)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='shelters.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='animal_photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='animals.animal')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteAnimal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='animals.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('treatment', 'Treatment'), ('surgery', 'Surgery'), ('checkup', 'Checkup'), ('spay_neuter', 'Spay/Neuter')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('date_administered', models.DateField()),
                ('veterinarian', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='medical_records/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField(default=dict)),
                ('notify_by_email', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['species', 'status'], name='animals_ani_species_deaf31_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['shelter', 'status'], name='animals_ani_shelter_ff7eb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteanimal',
            unique_together={('user', 'animal')},
        ),
    ]
