# Generated by Django 6.0.7 on 2026-07-12 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_role",
                    models.CharField(
                        choices=[("client", "Client"), ("vet", "Vet")], max_length=20
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("appointment", "Appointment"),
                            ("medicine", "Medicine Reminder"),
                            ("chat", "Chat Message"),
                            ("adoption", "Adoption"),
                            ("lost_found", "Lost and Found"),
                            ("report", "Report"),
                            ("system", "System"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "created_at"],
                        name="notificatio_recipie_86ea8b_idx",
                    ),
                    models.Index(
                        fields=["recipient_role", "created_at"],
                        name="notificatio_recipie_41acf2_idx",
                    ),
                ],
            },
        ),
    ]
