# Generated by Django 5.0.6 on 2026-07-03 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('reference_check', 'Reference Check'), ('meet_and_greet_scheduled', 'Meet & Greet Scheduled'), ('approved', 'Approved'), ('denied', 'Denied'), ('withdrawn', 'Withdrawn'), ('finalized', 'Finalized')], default='submitted', max_length=30)),
                ('household_info', models.JSONField(default=dict)),
                ('reason_for_adopting', models.TextField(blank=True)),
                ('availability_for_visit', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('denial_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='animals.animal')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adoption_fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('contract_document', models.FileField(blank=True, null=True, upload_to='adoption_contracts/')),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to=settings.AUTH_USER_MODEL)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_record', to='animals.animal')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_record', to='applications.adoptionapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('id', 'Government ID'), ('landlord_approval', 'Landlord Approval'), ('vet_reference', 'Vet Reference'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(upload_to='application_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.adoptionapplication')),
            ],
        ),
        migrations.CreateModel(
            name='MeetAndGreet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_home_visit', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meet_and_greets', to='applications.adoptionapplication')),
            ],
        ),
        migrations.CreateModel(
            name='PostAdoptionCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('adoption_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='applications.adoptionrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='adoptionapplication',
            index=models.Index(fields=['animal', 'status'], name='application_animal__696acc_idx'),
        ),
    ]
